include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint

linter:
  rules:
    - always_put_required_named_parameters_first
    - avoid_positional_boolean_parameters
    - avoid_slow_async_io
    - avoid_unused_constructor_parameters
    - cancel_subscriptions
    - cascade_invocations
    - close_sinks
    - combinators_ordering
    - comment_references
    - diagnostic_describe_all_properties
    - directives_ordering
    - discarded_futures
    - eol_at_end_of_file
    - no_runtimeType_toString
    - no_self_assignments
    - prefer_double_quotes
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_relative_imports
    - require_trailing_commas
    - sort_constructors_first
    - sort_pub_dependencies
    - sort_unnamed_constructors_first
    - tighten_type_of_initializing_formals
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_breaks
    - unnecessary_lambdas
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_statements
    - use_colored_box
    - use_decorated_box
    - use_enums
    - use_named_constants
