name: splash_green
description: "Splash the world with green 💚"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flame: ^1.17.0
  flutter:
    sdk: flutter

dev_dependencies:
  alf_lints:
    git: https://github.com/saibot-l/alf-lints.git
  custom_lint: ^0.6.4
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/klondike/sprites.png
    - assets/images/space_shooter/bullet.png
    - assets/images/space_shooter/enemy.png
    - assets/images/space_shooter/explosion.png
    - assets/images/space_shooter/spaceship.png
    - assets/images/space_shooter/stars_0.png
    - assets/images/space_shooter/stars_1.png
    - assets/images/space_shooter/stars_2.png
    - assets/images/splash_green/watercolor_splats.png
  uses-material-design: true
