name: Deployable Branch
on:
  push:
    branches:
      - main

jobs:
  static_analysis:
    name: Static analysis
    uses: ./.github/workflows/static_analysis.yaml
  deploy:
    name: Deploy
    needs: static_analysis
    uses: ./.github/workflows/deploy.yaml
